global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: triton
    metrics_path: /metrics
    static_configs:
      - targets: ["triton:8002"]

  - job_name: inference-gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]
